source :rubygems

# PostgreSQL driver
gem 'pg'

# Sinatra driver
gem 'sinatra'
gem 'sinatra-contrib'

# Use Thin for our web server
gem 'thin'

gem 'activesupport'
gem 'activerecord'

gem 'rake'

gem 'shotgun'

group :test do
  gem 'faker'
  gem 'rspec'
end

gem 'omniauth-facebook' # Facebook authentication
gem "koala", "~> 2.4"           # Facebook API