source :rubygems

# PostgreSQL driver
gem 'pg'

# Sinatra driver
gem 'sinatra'
gem 'sinatra-contrib'

# Use Thin for our web server
gem 'thin'

gem 'activesupport'
gem 'activerecord'

gem 'rake'

gem 'shotgun'

group :test do
  gem 'faker'
  gem 'rspec'
end

gem 'bcrypt'
gem 'carrierwave', '>= 1.0.0.beta', '< 2.0'
gem 'mini_magick'